# Dados RADAR Jovens na Pandemia

In [1]:
import pandas as pd
import os
import shutil
import datetime as dt
import filecmp as fc

In [2]:
randomizacoes = pd.read_csv("/Users/pedrozuccolo/Desktop/RADAR_JNP/randomizacoes.csv")

In [5]:
randomizacoes

,partic.\n(n),id,tcle_data,tria_filho_nome,Unnamed: 4,tria_dn_filho,tria_idd_filho,avaliação,horário,Avaliador,grupo
0,1,65 Flávia do Prado Lopes,08/11/21,Isaque do Prado Lopes,masc,04/04/09,12.0,10-Nov,18h,Marina,1.0
1,2,64 Matuska Souza Ribeiro,08/11/21,Pedro,masc,17/01/08,13.0,11-Nov,17h,Marina,2.0
2,3,66 Karina tamazi loureiro souza,09/11/21,Enzo Alexandre loureiro de Souza,masc,23/08/13,8.0,12-Nov,10h,Alex,2.0
3,4,82 Viviane Lima Santos,11/11/21,Natalia,fem,23/10/12,9.0,13-Nov,14h,Monicke,1.0
4,5,90 Virgínia Jane Oliveira de Souza,12/11/21,Enzo Gabriel Souza de Sá,masc,27/08/13,8.0,16-Nov,9hs,Giovanna,1.0
...,...,...,...,...,...,...,...,...,...,...,...
275,276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#extracting Ids from id column

randomizacoes["id"] = randomizacoes["id"].str.strip()

In [3]:
#list of data available
data_list = os.listdir("dados_JNP")

In [4]:
len(data_list)

25

In [6]:
for folders in data_list:
    print(folders)

74ca7255-26ef-441f-a008-ae869623714b
.DS_Store
2b6894fc-6b00-45df-902e-6a0c47613424
77facf4e-2073-42ba-a58a-02841b528baf
9d3bc8c2-7d53-43ce-abaa-1537296ba1a5
66f04d71-d589-4dcc-a607-a64bd0c550eb
3692f16a-8995-4c1b-a384-d5e5114aea8f
70f90da4-108c-4e17-80f6-6f09e37a3948
c4005ebb-e639-4dd6-9eb1-7d4c7b77201f
6a0dae67-3311-401a-9cb0-35fd9487cb0d
abeccbf1-dfce-4258-81f1-d3f08e8f2c8e
32851bd5-b187-4d97-9c68-27bac17df979
defccd69-3e27-432a-9aec-ece9b916b23a
3c7f0b96-755e-446b-b11b-91960e77b95f
08b6042b-b27a-4062-b308-12736d5ad027
1454da5b-7a55-47ec-ae9e-589091fee3f8
a90ee5f0-7e6a-43a6-9ea6-a30f77807732
8d3114be-ffac-411d-be23-f0ae91a70850
957bf104-3bb0-4f86-9c5e-12b38b7fab2c
1ee0d2a6-f401-4251-be92-2d3ce60fb965
bdb58fa0-52fc-4682-a0c2-7baa4b45eaa2
9a5ef52a-4359-496c-84f1-37b29a0bd012
e77ce99a-090c-44dc-9a2d-f04234cf5a2e
cefa9fa2-bc6f-4f8a-831f-60dbd50c0643
b78570cf-bec1-4914-aeaa-8103044bfee1

In [9]:
id_id = pd.read_csv("id_id.csv")

In [10]:
id_id = id_id[["id redcap", "id sistema", "início coleta"]]

In [11]:
id_id

   id redcap                            id sistema início coleta
0       test  08b6042b-b27a-4062-b308-12736d5ad027     7/23/2022
1       2652  1ee0d2a6-f401-4251-be92-2d3ce60fb965      8/2/2022
2       3068  2b6894fc-6b00-45df-902e-6a0c47613424      8/3/2022
3       2245  32851bd5-b187-4d97-9c68-27bac17df979     7/11/2022
4       2677  3692f16a-8995-4c1b-a384-d5e5114aea8f      8/1/2022
5       1979  74ca7255-26ef-441f-a008-ae869623714b    07/05/2022
6       1898  77facf4e-2073-42ba-a58a-02841b528baf      7/5/2022
7       1999  8d3114be-ffac-411d-be23-f0ae91a70850     6/25/2022
8       1913  957bf104-3bb0-4f86-9c5e-12b38b7fab2c      7/1/2022
9       2469  9a5ef52a-4359-496c-84f1-37b29a0bd012     7/23/2022
10      1861  9d3bc8c2-7d53-43ce-abaa-1537296ba1a5    06/27/2022
11      2178  a90ee5f0-7e6a-43a6-9ea6-a30f77807732      7/6/2022
12      2019  abeccbf1-dfce-4258-81f1-d3f08e8f2c8e     6/30/2022
13      2103  b78570cf-bec1-4914-aeaa-8103044bfee1     6/30/2022
14      2200  bdb58fa0-52fc-4682-a0c2-7baa4b45eaa2      7/7/2022
15      1497  c4005ebb-e639-4dd6-9eb1-7d4c7b77201f     6/23/2022
16      1693  defccd69-3e27-432a-9aec-ece9b916b23a    06/23/2022
17      2333  e77ce99a-090c-44dc-9a2d-f04234cf5a2e     7/21/2022
18       NaN                                   NaN           NaN

# Organizing data

# Organizing data according to each measure
ref: https://radar-base.org/index.php/data-sensors/

## Device info

## Relative location

## Nearby bluetooth devices

## User interaction

In [ ]:
#iterate over first level
for folders in os.listdir(parent_directory):
    
    #for each item that is a directory, then:
    if not folders.startswith("."):
        
        #iterate over second level:
        for subfolders in os.listdir(parent_directory + folders):
           
            #if folder in second levels matches the target, then:
            if subfolders == target_directory:
                
                #then iterate over the files
                for files in os.listdir(parent_directory + folders + "/" + subfolders):
                    
                    #save origin path in a variable
                    origin = parent_directory + folders + "/" + subfolders + "/" + files
                    
                    #split file name and save name and extension in separate variables
                    data = os.path.splitext(files)
                    name = data[0]
                    extension = data[1]
                    
                    #make a new name based on first level
                    new_base = name + "_"+ folders + extension
                    
                    #make a path based on this new name
                    new_name = os.path.join(destination_directory, new_base)
                    
                    #move file from origin folder to destination folder and rename the file
                    shutil.move(origin, new_name)

## Application uptime

In [3]:
file = "/Users/pedrozuccolo/Desktop/RADAR-Analyses/JNP/dados_JNP/1454da5b-7a55-47ec-ae9e-589091fee3f8/application_device_info/20220923_2000.csv.gz"

import gzip

with gzip.open(file, 'rb') as f:
    file_content = f.read()
    print(file_content)

b'key.projectId,key.userId,key.sourceId,value.time,value.manufacturer,value.model,value.operatingSystem,value.operatingSystemVersion,value.operatingSystemVersionCode,value.appVersion,value.appVersionCode\nJovens_na_Pandemia,1454da5b-7a55-47ec-ae9e-589091fee3f8,c0f1cecb-0168-4907-91b3-6e968ecd6247,1.663964274752E9,motorola,moto g(20),ANDROID,11,30,1.0.11-playStore,50\n'